import type {
  Knowledge,
  Category,
  Tag,
  Block,
  FileRecord,
} from "@/types";

// ──────────────────────────────────────────────
// Categories
// ──────────────────────────────────────────────

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Networking",
    description: "VPN, DNS, DHCP, firewall, and connectivity issues",
    color: "#3b82f6",
    icon: "Network",
    createdAt: new Date("2025-11-01"),
    updatedAt: new Date("2025-11-01"),
    _count: { knowledge: 12 },
  },
  {
    id: "cat-2",
    name: "Hardware",
    description: "Laptops, printers, monitors, docking stations",
    color: "#ef4444",
    icon: "Monitor",
    createdAt: new Date("2025-11-02"),
    updatedAt: new Date("2025-11-02"),
    _count: { knowledge: 8 },
  },
  {
    id: "cat-3",
    name: "Software",
    description: "OS issues, application crashes, installation guides",
    color: "#8b5cf6",
    icon: "AppWindow",
    createdAt: new Date("2025-11-03"),
    updatedAt: new Date("2025-11-03"),
    _count: { knowledge: 15 },
  },
  {
    id: "cat-4",
    name: "Security",
    description: "Account lockouts, phishing, permissions, MFA",
    color: "#f97316",
    icon: "Shield",
    createdAt: new Date("2025-11-04"),
    updatedAt: new Date("2025-11-04"),
    _count: { knowledge: 6 },
  },
  {
    id: "cat-5",
    name: "Email & Communication",
    description: "Outlook, Teams, email flow, calendar issues",
    color: "#06b6d4",
    icon: "Mail",
    createdAt: new Date("2025-11-05"),
    updatedAt: new Date("2025-11-05"),
    _count: { knowledge: 9 },
  },
];

// ──────────────────────────────────────────────
// Tags
// ──────────────────────────────────────────────

export const MOCK_TAGS: Tag[] = [
  { id: "tag-1", name: "VPN", color: "#3b82f6", createdAt: new Date("2025-11-01"), _count: { knowledge: 5 } },
  { id: "tag-2", name: "Windows 11", color: "#8b5cf6", createdAt: new Date("2025-11-01"), _count: { knowledge: 8 } },
  { id: "tag-3", name: "Printer", color: "#ef4444", createdAt: new Date("2025-11-01"), _count: { knowledge: 3 } },
  { id: "tag-4", name: "Active Directory", color: "#f97316", createdAt: new Date("2025-11-02"), _count: { knowledge: 7 } },
  { id: "tag-5", name: "Outlook", color: "#06b6d4", createdAt: new Date("2025-11-02"), _count: { knowledge: 4 } },
  { id: "tag-6", name: "Azure", color: "#22c55e", createdAt: new Date("2025-11-03"), _count: { knowledge: 6 } },
  { id: "tag-7", name: "MFA", color: "#eab308", createdAt: new Date("2025-11-03"), _count: { knowledge: 2 } },
  { id: "tag-8", name: "PowerShell", color: "#ec4899", createdAt: new Date("2025-11-04"), _count: { knowledge: 9 } },
];

// ──────────────────────────────────────────────
// Blocks
// ──────────────────────────────────────────────

const MOCK_BLOCKS_1: Block[] = [
  { id: "blk-1", knowledgeId: "k-1", type: "HEADING", order: 0, content: "Problem Description", metadata: null, createdAt: new Date(), updatedAt: new Date() },
  { id: "blk-2", knowledgeId: "k-1", type: "PARAGRAPH", order: 1, content: "User reports that the VPN client disconnects randomly every 10–15 minutes. This occurs on both Wi-Fi and ethernet connections.", metadata: null, createdAt: new Date(), updatedAt: new Date() },
  { id: "blk-3", knowledgeId: "k-1", type: "HEADING", order: 2, content: "Troubleshooting Steps", metadata: null, createdAt: new Date(), updatedAt: new Date() },
  { id: "blk-4", knowledgeId: "k-1", type: "STEP", order: 3, content: "Check VPN client version. Ensure it is at least v4.10.06079.", metadata: { stepNumber: 1 }, createdAt: new Date(), updatedAt: new Date() },
  { id: "blk-5", knowledgeId: "k-1", type: "STEP", order: 4, content: "Verify network adapter settings. Disable power saving on the NIC.", metadata: { stepNumber: 2 }, createdAt: new Date(), updatedAt: new Date() },
  { id: "blk-6", knowledgeId: "k-1", type: "STEP", order: 5, content: "Flush DNS cache: ipconfig /flushdns and restart the VPN service.", metadata: { stepNumber: 3 }, createdAt: new Date(), updatedAt: new Date() },
  { id: "blk-7", knowledgeId: "k-1", type: "PARAGRAPH", order: 6, content: "If the issue persists, escalate to the Network Engineering team with VPN client logs.", metadata: null, createdAt: new Date(), updatedAt: new Date() },
];

// ──────────────────────────────────────────────
// Knowledge
// ──────────────────────────────────────────────

export const MOCK_KNOWLEDGE: Knowledge[] = [
  {
    id: "k-1",
    title: "VPN Disconnects Randomly on Windows 11",
    slug: "vpn-disconnects-randomly-windows-11",
    summary: "Troubleshooting guide for intermittent VPN drops on Windows 11 machines using Cisco AnyConnect.",
    type: "INCIDENT",
    status: "PUBLISHED",
    source: null,
    categoryId: "cat-1",
    authorId: "user-1",
    createdAt: new Date("2025-12-01"),
    updatedAt: new Date("2025-12-15"),
    category: MOCK_CATEGORIES[0],
    tags: [{ tag: MOCK_TAGS[0] }, { tag: MOCK_TAGS[1] }],
    blocks: MOCK_BLOCKS_1,
  },
  {
    id: "k-2",
    title: "Setting Up New Printer on Print Server",
    slug: "setting-up-new-printer-print-server",
    summary: "Step-by-step documentation for adding a network printer to the Windows Print Server.",
    type: "DOCUMENTATION",
    status: "PUBLISHED",
    source: null,
    categoryId: "cat-2",
    authorId: "user-1",
    createdAt: new Date("2025-12-03"),
    updatedAt: new Date("2025-12-10"),
    category: MOCK_CATEGORIES[1],
    tags: [{ tag: MOCK_TAGS[2] }],
    blocks: [],
  },
  {
    id: "k-3",
    title: "Outlook Calendar Sync Failure After Migration",
    slug: "outlook-calendar-sync-failure",
    summary: "Users cannot see updated calendar items after Exchange Online migration.",
    type: "INCIDENT",
    status: "DRAFT",
    source: null,
    categoryId: "cat-5",
    authorId: "user-1",
    createdAt: new Date("2025-12-05"),
    updatedAt: new Date("2025-12-05"),
    category: MOCK_CATEGORIES[4],
    tags: [{ tag: MOCK_TAGS[4] }, { tag: MOCK_TAGS[5] }],
    blocks: [],
  },
  {
    id: "k-4",
    title: "PowerShell Script: Bulk AD User Export",
    slug: "powershell-bulk-ad-user-export",
    summary: "Script to export all Active Directory users with department and manager fields to CSV.",
    type: "SCRIPT",
    status: "PUBLISHED",
    source: null,
    categoryId: "cat-3",
    authorId: "user-1",
    createdAt: new Date("2025-12-08"),
    updatedAt: new Date("2025-12-12"),
    category: MOCK_CATEGORIES[2],
    tags: [{ tag: MOCK_TAGS[3] }, { tag: MOCK_TAGS[7] }],
    blocks: [],
  },
  {
    id: "k-5",
    title: "MFA Reset Procedure for Locked-Out Users",
    slug: "mfa-reset-procedure-locked-out",
    summary: "Standard procedure for resetting MFA when a user loses access to their authenticator app.",
    type: "DOCUMENTATION",
    status: "PUBLISHED",
    source: null,
    categoryId: "cat-4",
    authorId: "user-1",
    createdAt: new Date("2025-12-10"),
    updatedAt: new Date("2025-12-14"),
    category: MOCK_CATEGORIES[3],
    tags: [{ tag: MOCK_TAGS[6] }, { tag: MOCK_TAGS[5] }],
    blocks: [],
  },
  {
    id: "k-6",
    title: "Azure AD Conditional Access Quick Reference",
    slug: "azure-ad-conditional-access-reference",
    summary: "Quick reference card for common Conditional Access policies and their effects.",
    type: "RESOURCE",
    status: "PUBLISHED",
    source: "https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/",
    categoryId: "cat-4",
    authorId: "user-1",
    createdAt: new Date("2025-12-12"),
    updatedAt: new Date("2025-12-13"),
    category: MOCK_CATEGORIES[3],
    tags: [{ tag: MOCK_TAGS[5] }, { tag: MOCK_TAGS[3] }],
    blocks: [],
  },
  {
    id: "k-7",
    title: "New Hire Laptop Setup Checklist",
    slug: "new-hire-laptop-setup-checklist",
    summary: "Pre-deployment checklist for provisioning a new hire Windows laptop with all standard software.",
    type: "CHECKLIST",
    status: "PUBLISHED",
    source: null,
    categoryId: "cat-2",
    authorId: "user-1",
    createdAt: new Date("2025-12-14"),
    updatedAt: new Date("2025-12-15"),
    category: MOCK_CATEGORIES[1],
    tags: [{ tag: MOCK_TAGS[1] }],
    blocks: [],
  },
  {
    id: "k-8",
    title: "Quick Note: BitLocker Recovery Key Location",
    slug: "bitlocker-recovery-key-location",
    summary: "BitLocker recovery keys are stored in Azure AD under device properties.",
    type: "NOTE",
    status: "PUBLISHED",
    source: null,
    categoryId: "cat-4",
    authorId: "user-1",
    createdAt: new Date("2025-12-15"),
    updatedAt: new Date("2025-12-15"),
    category: MOCK_CATEGORIES[3],
    tags: [{ tag: MOCK_TAGS[5] }, { tag: MOCK_TAGS[1] }],
    blocks: [],
  },
];

// ──────────────────────────────────────────────
// Files
// ──────────────────────────────────────────────

export const MOCK_FILES: FileRecord[] = [
  {
    id: "file-1",
    name: "vpn-error-screenshot.png",
    originalName: "vpn-error-screenshot.png",
    mimeType: "image/png",
    type: "IMAGE",
    size: 245_760,
    storageKey: "uploads/vpn-error-screenshot.png",
    url: "/uploads/vpn-error-screenshot.png",
    uploadedById: "user-1",
    createdAt: new Date("2025-12-01"),
  },
  {
    id: "file-2",
    name: "printer-setup-guide.pdf",
    originalName: "printer-setup-guide.pdf",
    mimeType: "application/pdf",
    type: "PDF",
    size: 1_048_576,
    storageKey: "uploads/printer-setup-guide.pdf",
    url: "/uploads/printer-setup-guide.pdf",
    uploadedById: "user-1",
    createdAt: new Date("2025-12-03"),
  },
  {
    id: "file-3",
    name: "ad-user-export.ps1",
    originalName: "ad-user-export.ps1",
    mimeType: "text/plain",
    type: "TXT",
    size: 4_096,
    storageKey: "uploads/ad-user-export.ps1",
    url: "/uploads/ad-user-export.ps1",
    uploadedById: "user-1",
    createdAt: new Date("2025-12-08"),
  },
  {
    id: "file-4",
    name: "network-topology.docx",
    originalName: "network-topology.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    type: "DOCX",
    size: 524_288,
    storageKey: "uploads/network-topology.docx",
    url: "/uploads/network-topology.docx",
    uploadedById: "user-1",
    createdAt: new Date("2025-12-10"),
  },
  {
    id: "file-5",
    name: "deployment-logs.zip",
    originalName: "deployment-logs.zip",
    mimeType: "application/zip",
    type: "ZIP",
    size: 2_097_152,
    storageKey: "uploads/deployment-logs.zip",
    url: "/uploads/deployment-logs.zip",
    uploadedById: "user-1",
    createdAt: new Date("2025-12-14"),
  },
];
